### ISSUE TITLE
Usuário do lider do grupo

### ISSUE THREAD

**Issue by nukdown** [fga-verival/2019-2Grupo2#1]
Comentem nessa issue o usuário github do lider do grupo 2, que será responsável por dar privilegio para os demais membros neste repositório.

**Comment by rogerioo** [comment]
Opa! :smile:

**Comment by nukdown** [comment]
@rogerioo pronto man, só add a galera ai do seu grupo!

**Comment by rogerioo** [comment]
Vlw!
